### ISSUE TITLE
what is code?

### ISSUE THREAD

**Issue by batboyboy1990** [vadniks/ExchatgeDesktopClient#1]
This code can view item and trade on web ??

**Comment by vadniks** [comment]
No, this code is for secured message exchanging with other users through the server, content of a message will be hidden from the server via encryption (not yet implemented) and is now hidden from others. A particular client and the server both create an encrypted channel via sockets. For the messaging the binary protocol is used for controlling service messages and for routing users' messages. Also file exchange is planned to be implemented. Clients will be able to view the list of other clients, currently connected to the server and those who registered, but currently offline. Users will be able to create a conversation with others in order to be able to sent & receive messages.
